### ISSUE TITLE
my story (story1)

### ISSUE THREAD

**Issue by xmonader** [xmonader/org_testrepo#29]
# Tasks

- [ ] story1: first issue [1h] #[14](https://github.com/xmonader/org_testrepo/issues/14)
- [ ] story1: first issue [1h] #[18](https://github.com/xmonader/org_testrepo/issues/18)
- [ ] story1: first issue [1h] #[22](https://github.com/xmonader/org_testrepo/issues/22)
- [ ] story1: first issue [1h] #[26](https://github.com/xmonader/org_testrepo/issues/26)
- [ ] story1: first issue [1h] #[30](https://github.com/xmonader/org_testrepo/issues/30)

# Remaining Time: 5h

![Progress](http://progressed.io/bar/0)

# Waffle: [kanban](https://waffle.io/gig-projects/org_development?search=story1:&label=type_task)
