### ISSUE TITLE
my story (storykey)

### ISSUE THREAD

**Issue by xmonader** [xmonader/org_testrepo#54]
# Tasks

- [ ] storykey: first issue [1h] #[35](https://github.com/xmonader/org_testrepo/issues/35)
- [ ] storykey: second issue [2h] #[36](https://github.com/xmonader/org_testrepo/issues/36)
- [ ] storykey: first issue [1h] #[39](https://github.com/xmonader/org_testrepo/issues/39)
- [ ] storykey: second issue [2h] #[40](https://github.com/xmonader/org_testrepo/issues/40)
- [ ] storykey: first issue [1h] #[43](https://github.com/xmonader/org_testrepo/issues/43)
- [ ] storykey: second issue [2h] #[44](https://github.com/xmonader/org_testrepo/issues/44)
- [ ] storykey: first issue [1h] #[47](https://github.com/xmonader/org_testrepo/issues/47)
- [ ] storykey: second issue [2h] #[48](https://github.com/xmonader/org_testrepo/issues/48)
- [ ] storykey: first issue [1h] #[51](https://github.com/xmonader/org_testrepo/issues/51)
- [ ] storykey: second issue [2h] #[52](https://github.com/xmonader/org_testrepo/issues/52)
- [ ] storykey: first issue [1h] #[55](https://github.com/xmonader/org_testrepo/issues/55)
- [ ] storykey: second issue [2h] #[56](https://github.com/xmonader/org_testrepo/issues/56)

# Remaining Time: 18h

![Progress](http://progressed.io/bar/0)

# Waffle: [kanban](https://waffle.io/gig-projects/org_development?search=storykey:&label=type_task)
